# Generated by Django 2.1.3 on 2018-11-19 04:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('Scout', 'Scout'), ('Parent', 'Parent')], max_length=30)),
                ('commitment', models.CharField(choices=[('Intersted', "I'm interested"), ('Committed', "I'm committed")], max_length=30)),
                ('week1', models.BooleanField(verbose_name='30 Jun - 06 Jul')),
                ('week2', models.BooleanField(verbose_name='07 Jul - 13 Jul')),
                ('week3', models.BooleanField(verbose_name='14 Jul - 20 Jul')),
                ('week4', models.BooleanField(verbose_name='21 Jul - 27 Jul')),
                ('week5', models.BooleanField(verbose_name='28 Jul - 03 Aug')),
                ('week6', models.BooleanField(verbose_name='04 Aug - 10 Aug')),
                ('week7', models.BooleanField(verbose_name='11 Aug - 17 Aug')),
                ('week8', models.BooleanField(verbose_name='18 Aug - 24 Aug')),
                ('notes', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('link', models.URLField()),
                ('notes', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Required', 'Required'), ('Recommended', 'Recommended'), ('Optional', 'Optional')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Outfitter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('website', models.URLField()),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
