# Generated by Django 2.1.3 on 2018-11-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camper',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='camper',
            name='commitment',
            field=models.CharField(choices=[('Intersted', "I'm interested"), ('Committed', "I'm committed"), ('No', "I can't make it")], max_length=30),
        ),
        migrations.AlterField(
            model_name='camper',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
