# Generated by Django 2.1.3 on 2018-11-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwca', '0003_auto_20181119_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camper',
            name='commitment',
            field=models.CharField(choices=[('Interested', 'Interested'), ('Committed', 'Committed'), ('Cannot_Attend', 'Cannot Attend')], max_length=30),
        ),
        migrations.AlterField(
            model_name='camper',
            name='week1',
            field=models.BooleanField(verbose_name='Jul 30 - Jul 6'),
        ),
        migrations.AlterField(
            model_name='camper',
            name='week2',
            field=models.BooleanField(verbose_name='Jul 7 - Jul 13'),
        ),
        migrations.AlterField(
            model_name='camper',
            name='week3',
            field=models.BooleanField(verbose_name='Jul 14 - Jul 20'),
        ),
        migrations.AlterField(
            model_name='camper',
            name='week4',
            field=models.BooleanField(verbose_name='Jul 21 - Jul 27'),
        ),
        migrations.AlterField(
            model_name='camper',
            name='week5',
            field=models.BooleanField(verbose_name='Jul 28 - Aug 3'),
        ),
        migrations.AlterField(
            model_name='camper',
            name='week6',
            field=models.BooleanField(verbose_name='Aug 4 - Aug 10'),
        ),
        migrations.AlterField(
            model_name='camper',
            name='week7',
            field=models.BooleanField(verbose_name='Aug 11 - Aug 17'),
        ),
        migrations.AlterField(
            model_name='camper',
            name='week8',
            field=models.BooleanField(verbose_name='Aug 18 - Aug 24'),
        ),
    ]
